### ISSUE TITLE
Adding RabbitMQ to the stack

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/platform-deployment#54]
#### Description

Create our own image for RabbitMQ that allows us to have our own configurations (+ fancy uis?). 

#### DoD

Working Jenkins pipelines

#### Testing

Peer-review

**Comment by blankdots** [comment]
I have been testing the official image from https://hub.docker.com/_/rabbitmq  with the tag `rabbitmq:3.6.11-management` for the management plugin.
Configuration parameters available at: http://www.rabbitmq.com/configure.html#config-items  and we can modify the following file: `/etc/rabbitmq/rabbitmq.config`

**Comment by blankdots** [comment]
A possible dcompose YML file would be:
```yml
version: '3'
services:
  messagebroker:
    image: rabbitmq:3.6.11-management
    ports:
      - '4369:4369'
      - '5671:5671'
      - '5672:5672'
      - '15671:15671'
      - '15672:15672'
      - '25672:25672'
    environment:
        - RABBITMQ_DEFAULT_USER=user
        - RABBITMQ_DEFAULT_PASS=password
  fuseki:
    image: attxproject/attx-fuseki:1.0
    environment:
      - ADMIN_PASSWORD=pw123
    ports:
      - 3030:3030
  provservice:
    image: test/provapi
    depends_on:
        - messagebroker
        - fuseki
    environment:
        - MHOST=messagebroker
        - GHOST=fuseki
    links:
      - messagebroker:messagebroker
```
Parameters `MHOST` and `GHOST` are mandatory in this kind of setup, other parameters are `MUSER` and `MKEY` for messaging service which should correspond to `RABBITMQ_DEFAULT_USER` and `RABBITMQ_DEFAULT_PASS` and `GPORT`, `GKEY` which should correspond to the ones set up by fuseki and also `DS` for the dataset where to store the provenance.
