### ISSUE TITLE
Implement shared filesystem for Kontena

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/platform-deployment#55]
#### Description

Kontena implementation (=configurations and docs).

#### DoD

configurations and docs

#### Testing
Peer-review

**Comment by joasilva** [comment]
This task basically requires:
```
$ kontena volume create --driver local --scope stack attx-uv-shared
$ kontena volume create --driver local --scope stack attx-sb-shared
```

And then, in the Kontena YML stack file, declaring those volumes:
```
volumes:
  uv-shared:
    external:
      name: ${STACK}-uv-shared
  sb-shared:
    external:
      name: ${STACK}-sb-shared
```

And configuring the services to use them:
```
  gmapi:
    image: attxproject/gm-api:1.2
    volumes:
      - sb-shared:/attx-shared
    stateful: true
    ports:
      - "4302:4302"
    depends_on:
      - fuseki
      - es5
      - wfapi
```
But of course, we still have to decide the mount points of the containers for "/attx-shared".
