### ISSUE TITLE
Using Kontena's vault feature for secrets

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/platform-deployment#60]
#### Description

Move messagebroker credentials to the vault.

#### DoD
Working example.

#### Testing
Peer review

**Comment by joasilva** [comment]
We need to store secrets for:
MYSQL:
- MYSQL_ROOT_PASSWORD: "UV"
- MYSQL_PASSWORD: "UV"

SHARED:
- UV_DATABASE_SQL_PASSWORD: "UV"

FUSEKI:
- ADMIN_PASSWORD=pw123

**Comment by joasilva** [comment]
Here's how to use the Kontena Vault to store secrets, asking interactively for their  values (passwords) when the stack is installed:

```
variables:
  mysql_root_password:
    type: string
    from:
      vault: mysql-root-password
      prompt: Enter a root password for MySQL or leave empty to auto generate
      random_string: 16
    to:
      vault: mysql-root-password

  mysql_password:
    type: string
    from:
      vault: mysql-password
      prompt: Enter a DB password for MySQL or leave empty to auto generate
      random_string: 16
    to:
      vault: mysql-password



services:

  mysql:
    image: attxproject/unified-views-mariadb:stable-1.2
    ports:
      - "3306:3306"
    stateful: true
    secrets:
      - secret: mysql-root-password
        name: MYSQL_ROOT_PASSWORD
        type: env
      - secret: mysql-password
        name: MYSQL_PASSWORD
        type: env
```
