### ISSUE TITLE
Investigate how to setup vault for Docker SWARM

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/platform-deployment#62]
#### DoD
Documentation 

#### Testing
Peer-review

**Comment by joasilva** [comment]
Secrets in Docker Swarm require creation before deployment: `docker secret create SECRET VALUE`

**Comment by joasilva** [comment]
Initial version pushed to https://github.com/ATTX-project/platform-deployment/blob/dev/swarm-mode-cpouta/attx-swarm-secrets.yml

Requires creation of  "mysql_root_password" secret beforehand:
```
madeira@lx6-hulib-2:~$ echo "iamroot!" | docker secret create mysql_root_password -
zx7n3fyo3inaco5ms7t3gmcru
madeira@lx6-hulib-2:~$ docker secret inspect mysql_root_password
[
    {
        "ID": "zx7n3fyo3inaco5ms7t3gmcru",
        "Version": {
            "Index": 8130
        },
        "CreatedAt": "2017-10-18T13:46:34.020798502Z",
        "UpdatedAt": "2017-10-18T13:46:34.020798502Z",
        "Spec": {
            "Name": "mysql_root_password",
            "Labels": {}
        }
    }
]
```

**Comment by joasilva** [comment]
Following more intensive manual testing, I've reached the conclusion that the current docker-compose syntax doesn't work because it assigns to the ENV variable the literal name of the secret, and not its value. Troubleshooting continues.

**Comment by joasilva** [comment]
More troubleshooting, trying out the "MYSQL_ROOT_PASSWORD_FILE" environment variable (from https://hub.docker.com/_/mysql/):


```
version: "3.1"
services:

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/my_secret
    secrets:
      - source: my_secret
        mode: 0444

secrets:
  my_secret:
    file: ./my_secret.txt
```

**Comment by joasilva** [comment]
Applying the syntax above to our stack:

```
version: '3.1'
services:

  mysql:
    image: attxproject/unified-views-mariadb:stable-1.2
#    volumes:
#      - /uv-data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/my_secret
    secrets:
      - source: my_secret
        mode: 0444
    networks:
      - attx
    deploy:
      placement:
        constraints: [node.hostname == attx-swarm-1]
```
